---

- name: users > Templates
  template:
    src:   "{{ item.template|default(elao_ohmyzsh_users_template) }}"
    dest:  "{{ item.home|default('/root' if item.user == 'root' else '/home/' ~ item.user) }}/.zshrc"
    owner: "{{ item.user }}"
  with_items: elao_ohmyzsh_users

- name: users > Shells
  user:
    name: "{{ item.user }}"
    shell: /bin/zsh
  with_items: elao_ohmyzsh_users
