- name: clone bidracer-ui git repo
  git: repo=https://github.com/bidracer/bid-racer-ui.git
       dest=/home/bidracer/bidracer-ui
       accept_hostkey=yes
  sudo: yes
  when: orchestrate
  
- name: Change the file permissions for the repo folder
  file: path=/home/bidracer/bidracer-ui
        state=directory
        owner=bidracer
        mode=0777
        group=sudo
        recurse=yes

- name: Create a symlink /home/bidracer/bidracer-ui to /var/www/bidracer
  file: >
    src=/home/bidracer/bidracer-ui
    dest=/var/www/bidracer
    state=link
  sudo: yes
