---
apache_daemon: apache2
apache_server_root: /etc/apache2
apache_sites_available_path: /etc/apache2/sites-available
apache_sites_enabled_path: /etc/apache2/sites-enabled
apache_default_vhost: "{{ apache_sites_enabled_path }}/000-default*"
apache_packages:
    - apache2
    - apache2-mpm-prefork
    - apache2-utils
    - apache2.2-bin
apache_mods_enabled:
  - rewrite.load

# ex: ft=ansible et ts=2 sw=2:
