---
# This playbook bootstraps the bidracer-ui server
- hosts: all
  remote_user: root
  vars_files:
    - ./vars/main.yml
  roles:
    - role: debian-bootstrap
      when: orchestrate
    - role: swarup-apache
      when: orchestrate
    - role: geerlingguy-mysql
      when: orchestrate
    - role: geerlingguy-nodejs
      when: orchestrate
    - role: bidracer-ui-git
      when: deploy-app
  tasks:
    - include_vars: ./vars/main.yml
    - name: install bower
      shell: npm install -g bower
      when: orchestrate
