---
# This playbook bootstraps the bidracer-ui server
- hosts: all
  remote_user: root
  vars_files:
    - ./vars/main.yml
  roles:
    - role: debian-bootstrap
      when: orchestrate
    - role: swarup-apache
      when: orchestrate
    - role: geerlingguy-mysql
      when: orchestrate
    - role: geerlingguy-nodejs
      when: orchestrate
    - role: bidracer-ui-git
      when: deploy_app
  tasks:
    - include_vars: ./vars/main.yml
    - name: install bower
      shell: npm install -g bower
      when: orchestrate
    # - name: Send notification email
    #   sendgrid:
    #     username: "{{ sendgrid_username }}"
    #     password: "{{ sendgrid_password }}"
    #     from_address: "{{ sendgrid_from_addr }}"
    #     to_addresses: "{{ sendgrid_to_addr }}"
    #     subject: {{ sendgrid_default_subject }}
    #     body: "{{ sendgrid_default_body }}"
    #   delegate_to: localhost
